# ----------------------- #
#      Site Settings      #
# ----------------------- #
title: "Hongyi Yang"  # 浏览器标签页显示的标题
name: "Hongyi Yang (杨弘毅)"
description: "Undergraduate Researcher in Optoelectronics & Quantum Physics"
url: "https://hongyiyangzju-byte.github.io" # 修改为你自己的 GitHub Page 链接
baseurl: ""
# ----------------------- #
#      Site Author        #
# ----------------------- #
author:
  name: "Hongyi Yang"
  avatar: "profile.png" # 请上传一张正方形照片到 /images/ 文件夹并命名为 profile.png
  bio: "Undergraduate Student<br>Zhejiang University" # 侧边栏简介
  location: "Hangzhou, China"
  email: "hongyiyangzju@gmail.com"
  googlescholar: "" # 如果有 Google Scholar 链接填在这里
  github: "yourusername" # 填入你的 GitHub 用户名
  linkedin: "yourusername" # 填入你的 LinkedIn 用户名

# ----------------------- #
#      Navigation         #
# ----------------------- #
# 这一部分通常在 _data/navigation.yml 中修改，但这里也可以开启侧边栏链接
