# ----------------------- #
#      Site Settings      #
# ----------------------- #
title: "Hongyi Yang"
name: "Hongyi Yang (杨弘毅)"
description: "Undergraduate Researcher in Optoelectronics & Quantum Physics"
url: "https://hongyiyangzju-byte.github.io"
baseurl: "" # 必须为空

# ----------------------- #
#      Site Author        #
# ----------------------- #
author:
  name: "Hongyi Yang"
  avatar: "profile.png" 
  bio: "Undergraduate Student<br>Zhejiang University"
  location: "Hangzhou, China"
  email: "hongyiyangzju@gmail.com"
  googlescholar: "" 
  github: "hongyiyangzju-byte" # 已帮你填入正确的用户名
  linkedin: "" 

# ----------------------- #
#      Site Structure     #
#    (以下内容绝对不能删)   #
# ----------------------- #
locale: "en-US"
analytics:
  provider: "" 
  google:
    tracking_id: ""

# Welcome to Jekyll!
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Pagination Settings
paginate: 10
paginate_path: "/page:num/"

# The following settings are necessary for the theme to run
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Search Settings
search: true
search_full_content: true
search_provider: lunr 

# SEO Settings
twitter:
  username: "" 

# Social Sharing
sharer:
    facebook: false
    twitter: true
    linkedin: true
    reddit: false

# HTML Compression
compress_html:
  clippings: all
  comments: [""]
  endings: all
  ignore:
    envs: []
  profile: false
  blanklines: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _publications
  - scope:
      path: "_publications"
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _teaching
  - scope:
      path: "_teaching"
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: "_talks"
      type: talks
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
